apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      version: 1.0.9
    name: nodejs-health-check
  spec: {}
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      version: 1.0.9
    name: nodejs-health-check-s2i
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: nodejs-health-check:1.0.9
    postCommit: {}
    resources: {}
    source:
      git:
        ref: ce21eaf
        uri: https://github.com/hrishin/nodejs-health-check.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: DockerImage
          name: bucharestgold/centos7-s2i-nodejs:10.x
        incremental: true
      type: Source
    triggers:
    - github:
        secret: PU4a4k2ysQewcvtR8mVnrVaaQ8MCumfLwk8fTOyE
      type: GitHub
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
kind: List
metadata: {}
