apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      version: 1.0.1
    name: nodejs-health-check-s2i
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: nodejs-health-check:1.0.1
    postCommit: {}
    resources: {}
    source:
      git:
        ref: 90fe608
        uri: https://github.com/hrishin/nodejs-health-check.git
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: DockerImage
          name: bucharestgold/centos7-s2i-nodejs:10.x
        incremental: true
      type: Source
    triggers: []
  status:
    lastVersion: 0
kind: List
metadata: {}
