apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      version: 1.0.1
    name: nodejs-health-check
  spec:
    lookupPolicy:
      local: true
kind: List
metadata: {}
