apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    jenkins.openshift.org/disable-sync-create-on: jenkins
    jenkins.openshift.org/generated-by: jenkins
    jenkins.openshift.org/job-path: hrishin/nodejs-health-check/master
  labels:
    openshift.io/gitRepository: nodejs-health-check
    space: testspace
  name: nodejs-health-check
  namespace: hshinde
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/hrishin/nodejs-health-check.git
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      env:
      - name: FABRIC8_SPACE
        value: testspace
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: secret101
    type: GitHub
  - generic:
      secret: secret101
    type: Generic
